### ISSUE TITLE
Isha prayer time is off by exactly 3 hours.

### ISSUE THREAD

**Issue by Shadowhawk100** [achaudhry/adhan#1]
I haven't had a chance to debug this yet but here is my crontab output:

25 5 * * * /usr/local/bin/omxplayer -o local /home/osmc/adhan/Adhan-fajr.mp3 > /dev/null 2>&1 # rpiAdhanClockJob
57 12 * * * /usr/local/bin/omxplayer -o local /home/osmc/adhan/Adhan-Makkah.mp3 > /dev/null 2>&1 # rpiAdhanClockJob
26 16 * * * /usr/local/bin/omxplayer -o local /home/osmc/adhan/Adhan-Makkah.mp3 > /dev/null 2>&1 # rpiAdhanClockJob
4 19 * * * /usr/local/bin/omxplayer -o local /home/osmc/adhan/Adhan-Makkah.mp3 > /dev/null 2>&1 # rpiAdhanClockJob
34 17 * * * /usr/local/bin/omxplayer -o local /home/osmc/adhan/Adhan-Makkah.mp3 > /dev/null 2>&1 # rpiAdhanClockJob

For some reason i'sha (the last entry) is coming in as 17:34 instead of 20:34. All the other prayer times are correct or off by 1 minute (not a big deal).

Here is approximately my lat/long from google maps:
lat = 34.131025
long = -117.673580
PT.setMethod('Makkah')

Do you have any ideas as to why i'sha is wrong? I will try to investigate this some more later if you can't.

Cool project otherwise 👍 
-Ibraheem

**Comment by achaudhry** [comment]
Hi Ibraheem,

First of all, so sorry for such a late response. My primary email address was set to my old work email so I must have missed the notification.

As to your issue, use ISNA as prayer method e.g. `PT.setMethod('ISNA')`. It stands for Islamic Society of North America and is the most commonly used one in NA. I just tested and it should fix the three hours difference you're seeing. 

Hope you get to use this project. It's been running at mine as well as a few family member's houses for a couple of years and has been working great.

**Comment by iCandypw** [comment]
Hi I'm in Qatar (Middle East) I'm having the same issue.

Prayer Times for today in Doha
=========================================
Fajr: 04:26
Sunrise: 05:47
Dhuhr: 11:18
Asr: 14:26
Maghrib: 16:48
Isha: 15:18
Midnight: 23:18

PT = PrayTimes()
PT.setMethod('Makkah')


#-------------------------- Test Code --------------------------

# sample code to run in standalone mode only
if __name__ == "__main__":
	from datetime import date
	print('Prayer Times for today in Doha \n'+ ('='* 41))
	times = PT.getTimes(date.today(), (25.2793 , 51.5225), +3)
	for i in ['Fajr', 'Sunrise', 'Dhuhr', 'Asr', 'Maghrib', 'Isha', 'Midnight']:
		print(i+ ': '+ times[i.lower()])

I'm trying to match the timings found on https://prayers.qa/

الصلاة |   | الفجر الشروق الظهر العصر المغرب العشاء | الفجر |   | الشروق |   | الظهر |   | العصر |   | المغرب |   | العشاء
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
الفجر |   | الشروق |   | الظهر |   | العصر |   | المغرب |   | العشاء
 
الأذان |   | 4:28 5:47 11:18 2:26 4:50 6:20 | 4:28 |   | 5:47 |   | 11:18 |   | 2:26 |   | 4:50 |   | 6:20
4:28 |   | 5:47 |   | 11:18 |   | 2:26 |   | 4:50 |   | 6:20
 
الإقامة |   | +25 - +20 +25 +10 +20 | +25 |   | - |   | +20 |   | +25 |   | +10 |   | +20
+25 |   | - |   | +20 |   | +25 |   | +10 |   | +20

Any help would be very appreciated
