### ISSUE TITLE
Adjust settings/Athan MP3 files

### ISSUE THREAD

**Issue by oasaleh** [achaudhry/adhan#13]
I see in the Adtham folder there are a couple of different MP3 files for different Athans. How can I select between them?

**Comment by rehanhaider** [comment]
You will need to edit `updateprayertimes.py` file and swap the name.

**Comment by justgoodin** [comment]
You will need to edit `updateprayertime.py` file and swap the name.

**Comment by oasaleh** [comment]
Thank you.
