### ISSUE TITLE
Bluetooth Support

### ISSUE THREAD

**Issue by oasaleh** [achaudhry/adhan#14]
Is there a way to get it to run over connected Bluetooth speakers? I tried it and unfortunately it does not work. It must be connected through a 3.5mm jack.

**Comment by rehanhaider** [comment]
Are you using Raspberry Pi 3b+ or 4 ?

**Comment by oasaleh** [comment]
I'm using Raspberry Pi 4. I got it to connect to a bluetooth speaker but the sound doesn't come out.

**Comment by rehanhaider** [comment]
I'm afraid that is probably due to a known issue with Raspberry Pi where Alsa sound mixer stops working on Bluetooth stream. You might want to Google for a fix, I don't have a Pi 4 so won't be able to reproduce and test a fix.

**Comment by oasaleh** [comment]
Thank you for letting me know!
