### ISSUE TITLE
Trying to run this project on a Mac!

### ISSUE THREAD

**Issue by Zamy97** [achaudhry/adhan#8]
Was inspired by [Hossam Hammady](https://github.com/hammady) to open this as an issue as other people might have faced this issue as well too.

I am just playing with the **praytimes.py** and **updateazantimer.py** and instead of playing the audio on a pi, I am trying to run this in my local mac with the help of crontab but what is confusing me is how could I work around this command that is used for **omxplayer** to play the audio file. `omxplayer -o local /home/pi/adhan/Adhan-fajr.mp3 > /dev/null 2>&1` How could I work around that in order to be able to able to play the Adhan on my local machine?

Also, it seems as my jobs get created using crontab on my local machine but the audio file never really plays. 

The other thing that I am wondering is that instead of using a Pi to run this what If I wanted to use my own server to get this job done, what would I need to do then to create the jobs and make sure the audio plays when the prayer time comes?

Any tips or suggestions would be appreciated.

Edit: It was mentioned by [Hammady](https://github.com/hammady) that [launchd](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/ScheduledJobs.html) might be helpful to run this project on a mac.

**Comment by achaudhry** [comment]
Hey @Zamy97 

See my responses below.

> How could I work around that in order to be able to able to play the Adhan on my local machine?
> Also, it seems as my jobs get created using crontab on my local machine but the audio file never really plays.

I haven't set this up on a mac personally but I just tried the following command and works fine on my mac. 
`44 19 * * * afplay ~/development/code/adhan/Adhan-Makkah.mp3 > /dev/null 2>&1` 

>The other thing that I am wondering is that instead of using a Pi to run this what If I wanted to use my own server to get this job done, what would I need to do then to create the jobs and make sure the audio plays when the prayer time comes?

In theory this should work if you have a linux based machine and a speaker plugged into it. Although, I'm not sure quite sure if I quite understand the scenario you have mentioned above. Like, are you trying to get it to work on a remote server? Why? 

Thanks for reaching out!
